services:
  bedrock:
    image: $DOCKER_REGISTRY/treasure-chest/treasure-chest:$IMAGE_TAG
    container_name: treasure-chest_website
    pull_policy: always
    network_mode: bridge
    restart: always
    ports:
      - $PORT:443
    env_file: .env
    volumes:
      - $VOL:/srv/bedrock/web/app/uploads
