services:
  mountainofwonders_website:
    image: $DOCKER_REGISTRY/treasure-chest/treasure-chest:$IMAGE_TAG
    container_name: mountainofwonders_$ENV_NAME
    pull_policy: always
    restart: always
    ports:
      - $PORT:443
    env_file: .env
    volumes:
      - $VOL:/srv/bedrock/web/app/uploads
