services:
  bedrock:
    image: ${DOCKER_REGISTRY}/treasure-chest/treasure-chest:latest
    container_name: bedrock
    network_mode: bridge
    restart: always
    ports:
      - 8081:80
    env_file: .env
    volumes:
      - /mnt/treasure_chest_uploads:/srv/bedrock/web/app/uploads
