name: Container deployment

on:
  workflow_call:
    inputs:
      ENV_NAME:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      ENV_NAME:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string

jobs:
  container_deploy:
    runs-on: ARM64

    env:
      DOCKER_HOST: ${{ vars[format('DOCKER_HOST_{0}', inputs.ENV_NAME)] }}

    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB }}

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Run docker container
        env:
          DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
          IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
          PORT: 8081
          VOL: /mnt/treasure-chest_uploads_STG
        run: |
          echo "${{ secrets[format('DOT_ENV_{0}', inputs.ENV_NAME)] }}" > .env
          docker compose up -d
