name: Image build pipeline

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
  workflow_dispatch:

jobs:
  image_build:
    runs-on: ARM64

    steps:
      - name: Display Selected Branch
        run: |
          echo "Using branch: ${{ inputs.branch || github.ref }}"

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled
          ref: ${{ inputs.branch || github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and no push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: false
          pull: true
          no-cache: true
          tags: ${{ vars.DOCKER_REGISTRY }}/treasure-chest/treasure-chest:latest

      - name: Push to registry
        run: |
          docker push ${{ vars.DOCKER_REGISTRY }}/treasure-chest/treasure-chest:latest
