name: STG deployment

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  image_build:
    uses: ./.github/workflows/image_build.yml
    secrets: inherit    

  deploy_stg:
    uses: ./.github/workflows/container_deploy.yml
    needs: image_build
    with:
      DOCKER_HOST: ${{ vars.DOCKER_HOST_STG }}
    secrets:
      DOT_ENV: ${{ secrets.ENV_STG }}
      SSH_PRIVATE_KEY_GITHUB: ${{ secrets.SSH_PRIVATE_KEY_GITHUB }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
