name: STG deployment

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  image_build:
    uses: ./.github/workflows/image_build.yml
    secrets: inherit    

  deploy_stg:
    runs-on: ARM64
    needs: image_build

    env:
      DOCKER_HOST: ${{ vars.DOCKER_HOST_STG }}
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}

    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB }}

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Run docker container
        run: |
          echo "${{ secrets.ENV_STG }}" > .env
          docker compose up -d
